# Perceptron
*Perceptron* is a neural network with just one layer.
It's a linear classifier that outputs a binary responce variable.
Therefore, the algorithm is called: "linear binary classifier".

### Linear separability:
1. Data must be cleanly separable into two classes
2. It must be LINEARLY separable

### Composed of elements:
1. Input layer
2. Weights & bias
3. Weighted sum
4. Activation function - mathematical function deployed on every unit of the NN.

All units of the same layer share the same activation function.

### Activation functions:
1. Linear Activation: in a single layer perceptron
2. Logistic Sigmoid: good for the final layer with binary outcomes
3. Threshold: good with binary data
4. ReLU: (rectified linear unit)
5. Softmax

## Setup

In [1]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report


In [2]:
from sklearn.linear_model import Perceptron

In [3]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [4]:
X[:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [6]:
standardize = StandardScaler()
standardized_X_train = standardize.fit_transform(X_train)
standardized_X_test = standardize.fit_transform(X_test)

In [7]:
standardized_X_train[:10]

array([[-0.79030818,  0.9871338 , -1.22945004, -1.08165034],
       [-0.4269481 ,  1.87945814, -1.06147964, -0.94960758],
       [ 0.66313215, -1.24367705,  0.78619481,  1.03103395],
       [ 0.78425218,  0.09480946,  1.06614548,  0.89899118],
       [-1.03254824, -1.24367705,  0.50624414,  0.76694841],
       [-0.91142821,  0.9871338 , -1.28544018, -1.08165034],
       [ 1.14761226, -0.12827162,  0.78619481,  0.76694841],
       [-0.91142821, -2.35908248, -0.05365721, -0.15735097],
       [-0.79030818,  1.65637706, -0.94949937, -0.94960758],
       [-1.15366827,  0.76405272, -1.11746977, -1.21369311]])

In [8]:
standardized_X_test[:10]

array([[ 1.10660574,  0.3833636 ,  0.19812786, -0.17636891],
       [-0.28827545, -0.41902533,  0.06304068, -0.02939482],
       [-0.42776356, -0.15156235,  0.46830221,  0.41152745],
       [ 0.40916515, -0.68648831,  0.13058427, -0.02939482],
       [ 0.96711762,  0.3833636 ,  0.87356374,  1.14639788],
       [-0.28827545, -2.29126617, -0.27467726, -0.76426526],
       [ 0.40916515, -0.15156235,  0.5358458 ,  0.70547562],
       [ 0.26967703,  0.3833636 ,  0.60338939,  1.14639788],
       [ 1.38558198,  1.45321551,  1.14373809,  1.44034606],
       [ 1.24609386, -0.15156235,  1.00865092,  0.85244971]])

In [9]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)
perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [10]:
y_pred = perceptron.predict(standardized_X_test)

In [11]:
print(y_test)
print(y_pred)

[1 1 2 1 2 1 2 2 2 2 2 0 0 1 0 2 1 1 2 2 2 0 2 1 2 1 2 0 1 1]
[0 1 1 1 2 1 1 2 2 2 1 0 0 1 0 1 1 0 2 2 1 0 1 1 2 1 2 0 1 0]


In [13]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.62      1.00      0.77         5
           1       0.57      0.73      0.64        11
           2       1.00      0.57      0.73        14

    accuracy                           0.70        30
   macro avg       0.73      0.77      0.71        30
weighted avg       0.78      0.70      0.70        30

